name: hasFlutterPassedReactnativeYet
description: A Dart Web App to compare GitHub stars of Flutter and React Native.
version: 0.2.1
homepage: https://piedcipher.github.io/hasFlutterPassedReactNativeYet/
author: piedcipher

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
